ground_segmentation:
  ros__parameters:
    n_threads: 10            # number of threads to use.

    r_min: 0.2                # 较小在上下坡时会存在近处坡面误判
    r_max: 10.0                   # maximum point distance.
    n_bins: 140                 # number of radial bins.
    n_segments: 360             # number of radial segments.

    max_dist_to_line: 0.3      # 较小离群点多

    sensor_height: 0.33       # sensor height above ground.
    min_slope: 0.0              # minimum slope of a ground line.
    max_slope: 0.4          # maximum slope of a ground line.
    max_fit_error: 0.075         # maximum error of a point during line fit.
    long_threshold: 1.0         # distance between points after which they are considered far from each other.
    max_long_height: 0.2        # maximum height change to previous point in long line.
    max_start_height: 0.2       # maximum difference to estimated ground height to start a new line.
    line_search_angle: 0.2      # how far to search in angular direction to find a line [rad].

    gravity_aligned_frame: "base_link_fake"   # Frame which has its z axis aligned with gravity. (Sensor frame if empty.)

    latch: false                # latch output topics or not
    visualize: false            # visualize segmentation result - USE ONLY FOR DEBUGGING

    input_topic: "/livox/lidar/pointcloud"
    obstacle_output_topic: "segmentation/obstacle"
    ground_output_topic: "segmentation/ground"